development:
  adapter: postgresql
  encoding: unicode
  database: rcop_development
  host: db
  user: postgres
  port: 5432
  pool: 5

test:
  adapter: postgresql
  database: rcop_test
  encoding: unicode

production:
  adapter: postgresql
  encoding: unicode
  database: rcop_production
  host: db
  user: postgres
  port: 5432
  pool: 3

